Добавлен список вложенных в html ссылок в класс ParsedHtml.
itis-anete/Search pull request #2
Opened 2019-10-30 17:38 UTC by SizovaDarya708

2019-10-31 12:57 UTC, DrunkRussianGun commented
Код хотя бы ручное тестирование проходил?

2019-11-21 11:41 UTC, DrunkRussianGun requested changes

2019-11-21 11:41 UTC, DrunkRussianGun commented on Search.IndexService/Internal/ParsedHtml.cs
> +        public List<string> Links;
Лучше всё-таки свойством сделать, а не полем
```suggestion
        public List<string> Links { get; set; };
```

2019-11-21 11:41 UTC, DrunkRussianGun commented on Search.IndexService/Internal/Parser.cs
> +                    if (el != null && el.Substring(0, 1) == "h")
Странная проверка на первый символ элемента. Зачем она нужна?

2019-11-21 11:41 UTC, DrunkRussianGun commented on Search.IndexService/Internal/Parser.cs
> +                string el;
Лучше объявить (и заодно проинициализировать) внутри цикла foreach

2019-11-21 11:53 UTC, SizovaDarya708 commented on Search.IndexService/Internal/Parser.cs
> +                    if (el != null && el.Substring(0, 1) == "h")
Поправлю - необходим для поиска конкретных ссылок

2019-11-21 11:54 UTC, SizovaDarya708 commented on Search.IndexService/Internal/Parser.cs
> +                string el;
Понял - принял

2019-11-21 12:09 UTC, DrunkRussianGun approved these changes

2019-11-21 12:09 UTC, merged